SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

COLLISION_DIST = 400

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
# Player1 & Player2 colors for ship & shot)

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100

SHOT_RADIUS = 5

SHRAPNEL_WIDTH = 2
SHRAPNEL_HEIGHT = 4
SHRAPNEL_LIFETIME = 0.6
